/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Appbar: typeof import('./src/components/Appbar.vue')['default']
    FilterForm: typeof import('./src/components/FilterForm.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    TransitNotes: typeof import('./src/components/TransitNotes.vue')['default']
  }
}
